version: "3.1"

services:
  database:
    container_name: pharmaguide
    build: ./database
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    container_name: fastapi
    build: ./api
    working_dir : /code/app
    command: python main.py
    environment:
      DEBUG: ${DEBUG}
      PORT: ${PORT}
      HOST: ${HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    volumes:
      - ./api/app:/code/app
    ports:
      - "8000:8000"
    depends_on: [database]