drop schema if exists Pharmaguide CASCADE;

CREATE SCHEMA PharmaGuide;

drop table if exists PharmaGuide.user_type;

create table PharmaGuide.user_type (
  id INT not null generated by default as identity,
  user_type VARCHAR(32),
  
  constraint pk_uty primary key (id)
);

DROP TABLE IF EXISTS PharmaGuide.user;

CREATE TABLE PharmaGuide.user (
  user_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50),
  username VARCHAR(50),
  password VARCHAR(25),
  email VARCHAR(52),
  type INT not NULL,
  
  CONSTRAINT pk_u PRIMARY KEY (user_id),
  constraint fk_ut foreign key (type) references PharmaGuide.user_type (id)
);

DROP TABLE IF EXISTS PharmaGuide.pharmacy;

CREATE TABLE PharmaGuide.pharmacy (
  pharmacy_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(100),
  lat DECIMAL,
  lng DECIMAL,
  contact VARCHAR(50),
  owner INT NOT NULL,
  
  CONSTRAINT pk_p PRIMARY KEY (pharmacy_id),
  CONSTRAINT fk_u FOREIGN KEY (owner) REFERENCES PharmaGuide.user (user_id)
);

DROP TABLE IF EXISTS PharmaGuide.pharmacy_image;

CREATE TABLE PharmaGuide.pharmacy_image (
  name VARCHAR(44) NOT NULL,
  pharmacy_id INT NOT NULL,
  
  CONSTRAINT pk_pi PRIMARY KEY (name),
  CONSTRAINT fk_ph FOREIGN KEY (pharmacy_id) REFERENCES PharmaGuide.pharmacy (pharmacy_id)
);


DROP TABLE IF EXISTS PharmaGuide.category_name;

CREATE TABLE PharmaGuide.category_name (
  category_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50),
  
  CONSTRAINT pk_cn PRIMARY KEY (category_id)
);


DROP TABLE IF EXISTS PharmaGuide.product;

CREATE TABLE PharmaGuide.product (
  product_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(60) NOT NULL,
  code VARCHAR(12) NOT NULL,
  description VARCHAR(200),  
  
  CONSTRAINT pk_prd PRIMARY KEY (product_id)
  );


DROP TABLE IF EXISTS PharmaGuide.product_category;

CREATE TABLE PharmaGuide.product_category (
  category_id INT NOT NULL,
  product_id INT NOT NULL,
  
  CONSTRAINT pk_pc PRIMARY KEY (product_id, category_id) ,
  CONSTRAINT fk_cn FOREIGN KEY (category_id) REFERENCES PharmaGuide.category_name (category_id),
  CONSTRAINT fk_pr FOREIGN KEY (product_id) REFERENCES PharmaGuide.product (product_id)
);

DROP TABLE IF EXISTS PharmaGuide.product_image;

CREATE TABLE PharmaGuide.product_image (
  name VARCHAR(44) NOT NULL,
  product_id INT NOT NULL,
  
  CONSTRAINT pk_pig PRIMARY KEY (name),
  CONSTRAINT fk_prd FOREIGN KEY (product_id) REFERENCES PharmaGuide.product (product_id)
);

DROP TABLE IF EXISTS PharmaGuide.inventory;

CREATE TABLE PharmaGuide.inventory (
  product_id INT NOT NULL,
  pharmacy_id INT NOT NULL,
  price DECIMAL not null,
  stock INT,
  
  CONSTRAINT pk_i PRIMARY KEY (product_id, pharmacy_id) ,
  CONSTRAINT fk_pri FOREIGN KEY (product_id) REFERENCES PharmaGuide.product (product_id),
  CONSTRAINT fk_phy FOREIGN KEY (pharmacy_id) REFERENCES PharmaGuide.pharmacy (pharmacy_id)
);

DROP TABLE IF EXISTS PharmaGuide.advertisement;

CREATE TABLE PharmaGuide.advertisement (
  advertisement_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  advertisement_title varchar(25) NOT NULL,
  advertisement_description varchar(50) NOT NULL,
  advertisement_image varchar(50) NULL,
  owner INT NOT NULL,
  
  CONSTRAINT pk_a PRIMARY KEY (advertisement_id),
  CONSTRAINT fk_u FOREIGN KEY (owner) REFERENCES PharmaGuide.user (user_id)
);